typography_spectrum: 0.12892075115814805
color:
  brandStrength: 0.41239498066715896
  lightness: 0.31958093494176865
  saturation: 0.14226227905601263
  rhythmicContrast: 0.9940850418061018
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
layout_spectrum: 0.8458182120230049
name: Dorit Noble - somatic coach and trainer
title: coaching leadership systems
